---
title: 28. 异常机制的处理原理
tag: [异常]
category: C++
---

>**三步骤：try——throw——catch** 

<!--more-->

```C++
#include<iostream>
using namespace std;
 
float Div(int a, int b){
	if(b == 0){
		throw b;  //抛出异常,从右边返回,return不执行,直接跳到catch
	}
	return a/b;  //从左边返回,返回类型为float
}
 
void main(){
	int a = 10;
	int b = 100;
	float result = 0.0f;
	try{
		float result = Div(a,b);
	}
	catch(int){  //针对类型进行 catch
		cout<<"Div Error, b == 0"<<endl;
	}
	catch(short){
		cout<<"Div Error, b == 0"<<endl;
	}
	catch(...){  //catch all,只能放到最后
		cout<<"Div Error, b == 0"<<endl;
	}
	cout<<"result = "<<result<<endl;
}
```

throw 是从右边抛出的，不执行下面的程序，直接执行 catch 程序。

**异常规范**

实际上 VC6.0 不支持，所以最好还是不写 throw。

```C++
float Div(int a, int b)throw(){
	if(b == 0){
		throw b;  //抛出异常,从右边返回,return不执行,直接跳到catch
	}
	return a/b;  //从左边返回,返回类型为float
}
```

<u>本文于 2018 年 8 月 4 日首发于 [CSDN](https://blog.csdn.net/wonz5130/article/details/81408286)。</u>	